*Exercise 2.95:* Define P_1, P_2, and P_3 to be the polynomials

    P_1 : x^2 - 2x + 1

    P_2 : 11x^2 + 7

    P_3 : 13x + 5

Now define Q_1 to be the product of P_1 and P_2 and Q_2 to be the
product of P_1 and P_3, and use `greatest-common-divisor' (*Note
Exercise 2-94::) to compute the GCD of Q_1 and Q_2.  Note that the
answer is not the same as P_1.  This example introduces noninteger
operations into the computation, causing difficulties with the GCD
algorithm.(8)  To understand what is happening, try tracing
`gcd-terms' while computing the GCD or try performing the division
by hand.

#+begin_src scheme :results silent
(define p1 (make-poly 'x (list (2 . 1) (1 . -2) (0 . 1))))
(define p2 (make-poly 'x (list (2 . 11) (0 . 7))))
(define p3 (make-poly 'x (list (1 . 13) (0 . 5))))

(define q1 (make-poly 'x (list (4 . 11) (3 . -22) (2 . 18) (1 . -14) (0 . 17))))
(define q2 (make-poly 'x (list (3 . 13) (2 . -21) (1 . 3) (0 . 5))))
#+end_src

I should have really kept all the code for this chapter in the same file. It is such a hassle to go through all the code from all the exercises to compile a system that would actually run this division operation successfully. I will make sure to do this in Chapter 3.

Essentially, the reason that we do not get P1 as the answer to ~greatest-common-divisor~ with arguments Q1 and Q2 is because the coefficients of the first terms in both Q1 and Q2 are prime. So when we divide the polynomials, the resulting coefficients will have to be rational numbers no matter how many times we multiply them. This is why we cannot get P1 as the answer to ~(greatest-common-divisor Q1 Q2)~.
